In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1,10).reshape(3,3)

In [4]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr2 = np.arange(10, 13).reshape(1,3)

In [6]:
print(arr2)

[[10 11 12]]


In [7]:
#concatenation
crr = np.concatenate([arr1, arr2], axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [8]:
crr = np.concatenate([arr1, arr2.T], axis=1)

In [9]:
print(crr)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [17]:
crr[1:][0]

array([ 4,  5,  6, 11])

In [18]:
crr[:,:]

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [19]:
crr[1:,1:]

array([[ 5,  6, 11],
       [ 8,  9, 12]])

In [23]:
crr[:,0]

array([1, 4, 7])

In [24]:
crr[:,1]

array([2, 5, 8])

In [25]:
crr[:,2]

array([3, 6, 9])

In [26]:
crr

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [27]:
crr[2,:]=10

In [28]:
crr

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [10, 10, 10, 10]])

In [29]:
crr[:,2] = 7

In [30]:
crr

array([[ 1,  2,  7, 10],
       [ 4,  5,  7, 11],
       [10, 10,  7, 10]])

In [ ]:
arr11 = np.range