### Lab1 : Numpy & Arrays

In [44]:
import numpy as np

In [45]:
np.__version__

'2.2.1'

In [46]:
arr1 = np.array([1,2,3,4,5,6,7])

In [47]:
print(arr1)

[1 2 3 4 5 6 7]


In [49]:
arr1.dtype

dtype('int64')

In [50]:
arr2 = np.arange(3,9)

In [51]:
print(arr2)

[3 4 5 6 7 8]


In [52]:
print(arr2[4])

7


In [53]:
arr2.dtype

dtype('int64')

In [56]:
#convert int array to float array
arr2 = np.array(arr2, dtype=np.float64)

In [57]:
arr2.dtype

dtype('float64')

In [58]:
arr2[1:3]

array([4., 5.])

In [59]:
len(arr2)

6

In [62]:
#Shape
arr2.shape

(6,)

In [63]:
#Dimensions
arr2.ndim

1

In [64]:
arr3 = np.array([[1,2,3],[4,5,6]])

In [65]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr3.shape

(2, 3)

In [67]:
arr3.ndim

2