In [1]:
import numpy as np

In [11]:
# Exercise 1
arr1 = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])

In [6]:
print(arr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [8]:
print("Length =", len(arr1))

Length = 3


In [9]:
print("Shape =", arr1.shape)

Shape = (3, 3, 2)


In [10]:
print("Dimentions =", arr1.ndim)

Dimentions = 3


In [13]:
#Exercise 1a: First 2D array from above 3D array

In [14]:
print(arr1[0])

[[1 2]
 [3 4]
 [5 6]]


In [22]:
print("Length =", len(arr1[0]))

Length = 3


In [17]:
print("Shape =", arr1[0].shape)

Shape = (3, 2)


In [18]:
print("Dimensions =", arr1[0].ndim)

Dimensions = 2


In [19]:
#Exercise 1b: First 1D array from 3D array

In [20]:
print(arr1[0][0])

[1 2]


In [21]:
print("Length =", len(arr1[0][0]))

Length = 2


In [23]:
print("Shape =", arr1[0][0].shape)

Shape = (2,)


In [24]:
print("Dimensions =", arr1[0][0].ndim)

Dimensions = 1
